# Generated by Django 3.0.8 on 2020-07-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='название предмета')),
                ('teacher', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.CharField(blank=True, max_length=2, null=True, verbose_name='оценка за первую аттестацию')),
                ('mark2', models.CharField(blank=True, max_length=2, null=True, verbose_name='оценка за вторую аттестацию')),
                ('mark3', models.CharField(blank=True, max_length=2, null=True, verbose_name='оценка за третью аттестацию')),
                ('summa_mark', models.IntegerField(blank=True, null=True, verbose_name='общая оценка')),
                ('avg_mark', models.IntegerField(blank=True, null=True, verbose_name='средняя оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='questionary.Student', verbose_name='студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='attestation.Subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Аттестация',
                'verbose_name_plural': 'Аттестации',
            },
        ),
    ]
